version = 0.1

[default.deploy.parameters]
stack_name = "susanoo"
resolve_s3 = true
s3_prefix = "susanoo"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
